import { Box, CssBaseline, Divider, ThemeProvider } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import Footer from "../Components/Footer/Footer";
import Hero from "../Components/HeroComponent/Hero";
import NavBar from "../Components/NavBar/NavBar";
import Header from "../Components/Projects/Header";
import Projects from "../Components/Projects/Projects";
import Services from "../Components/Services/Services";
import styles from "../styles/Home.module.css";
import { gsap } from "gsap/dist/gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
import { useEffect, useRef } from "react";

gsap.registerPlugin(ScrollTrigger);

export default function Home() {
  const app = useRef();

  useEffect(() => {
    const ctx = gsap.context(() => {
      gsap.to(".header", {
        scale: 2.5,
        scrollTrigger: {
          trigger: ".profile",
          start: "bottom center",
          scrub: 1.5,
        },
      });

      // background color change

      let sections = gsap.utils.toArray(".section");
      sections.forEach((section, idx) => {
        const bgPrev = idx === 0 ? "" : sections[idx - 1].dataset.bgcolor;
        const txtPrev = idx === 0 ? "" : sections[idx - 1].dataset.text;
        const bgCurrent = section.dataset.bgcolor;
        const textCurrent = section.dataset.text;

        ScrollTrigger.create({
          trigger: section,
          start: "top 20%",
          // markers: true,
          onEnter: () => {
            gsap.to("main", {
              backgroundColor: bgCurrent,
              color: textCurrent,
              overwrite: "auto",
            });
          },
          onLeaveBack: () => {
            gsap.to("main", {
              backgroundColor: bgPrev,
              color: txtPrev,
              overwrite: "auto",
            });
          },
        });
      });
    }, app);

    return () => ctx.revert();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main ref={app} style={{}}>
        {/* <ThemeProvider theme={theme}> */}
        <CssBaseline />
        <Hero />
        <Projects />
        {/* </ThemeProvider> */}
      </main>
      <footer className="footer">
        <Footer />
      </footer>
    </div>
  );
}
